---
- hosts: all
  gather_facts: no
  tasks:
  - name: Get user authorization token
    uri:
      url: "{{ grid_admin_base_url }}api/v3/authorize"
      method: POST
      body: {
        "username": "{{ grid_user }}",
        "password": "{{ grid_pass }}",
        "cookie": false,
        "csrfToken": false
      }
      body_format: json
      validate_certs: false
    register: auth
    no_log: false

  - name: print auth token
    debug:
      msg: "{{ auth.json.data }}"

  - name: create a user
    netapp.storagegrid.nac_sg_grid_user:
      api_url: "{{ grid_admin_base_url }}"
      auth_token: "{{ auth.json.data }}"
      validate_certs: false
      state: present
      full_name: ansibleuser200
      unique_name: user/ansibleuser200
      member_of: "group/ansiblegroup100"
      disable: false
